# Generated by Django 5.1.14 on 2026-02-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(help_text="e.g. 'The Land Down Under'", max_length=200)),
                ('guide_content', models.JSONField(blank=True, default=list, help_text='List of guide pages objects')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='universities/')),
                ('description', models.TextField()),
                ('ranking', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='country.country')),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
