# Generated by Django 5.1.14 on 2026-02-06 04:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_remove_country_guide_content_remove_country_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='guide_pages',
            field=wagtail.fields.StreamField([('cover', 1), ('text', 4), ('image', 7), ('end', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 0)]], {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sun', 'Sun'), ('landmark', 'Landmark'), ('globe', 'Globe'), ('coffee', 'Coffee'), ('graduation-cap', 'Graduation Cap'), ('music', 'Music'), ('book-open', 'Book Open'), ('briefcase', 'Briefcase')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 2), ('icon', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('image', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('content', 2)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='guide_title',
            field=models.CharField(blank=True, help_text='Title for the country guide', max_length=255, null=True),
        ),
    ]
